### ISSUE TITLE
[Feature Request] Allow to limit history to different views

### ISSUE THREAD

**Issue by Novack** [acoppes/unity-history-window#14]
I'd like to have the history only affecting Project View, for example.

**Comment by acoppes** [comment]
Not sure how to do it, I suppose I could check if the selected object is an asset or if it is in the scene maybe.

Also, there should be a way to enable/disable this, maybe in the settings or maybe a checkbox in the window itself to filter (project view, scene view, etc)

Feel free to make a pull request if you already have an idea on how to do it, the project code is really simple and small so it is really easy to iterate.

**Comment by Novack-** [comment]
Will work on it as soon as I can :)

**Comment by Novack** [comment]
I confess Im ashamed to have never came back to this, but just tried the preferences you added and they work like a charm. Well done, thank you!
Closing this one.
