### ISSUE TITLE
[Feature Request] Back / Forward Buttons on Project View

### ISSUE THREAD

**Issue by Novack** [acoppes/unity-history-window#15]
Pretty much what the title says. This would allow history navegation even when the History window is not directly visible.

**Comment by acoppes** [comment]
I believe I don't have a way to add buttons to the project view. I could add buttons to the history window, not sure if it is the same for you.  Also, there are two shortcuts for back and forward:

	
```
                [MenuItem("Window/Gemserk/Previous selection %#,")]
		public static void PreviousSelection()
		{
			selectionHistory.Previous ();
			Selection.activeObject = selectionHistory.GetSelection ();
		}

		[MenuItem("Window/Gemserk/Next selection %#.")]
		public static void Nextelection()
		{
			selectionHistory.Next();
			Selection.activeObject = selectionHistory.GetSelection ();
}
```


You could change them if you want other shortcuts.

**Comment by Novack-** [comment]
Thanks for the shortcuts man. Yes, buttons in the history windows would be nice!

**Comment by Novack-** [comment]
Will check if I can found a way to add buttons to the project view.

**Comment by Novack** [comment]
After some research, I think there is no way to add these buttons to the project view yet, we need to wait for Unity to move that window to the new UIElements code.
