### ISSUE TITLE
Exclude Runtime Assembly From Game Builds

### ISSUE THREAD

**Issue by nick-morhun** [acoppes/unity-history-window#18]
Hi, the usability of this package is awesome!
One minor issue I have found is with your runtime classes: they are included in game builds by default.

Just set Auto Referenced to false in the runtime asmdef.

**Comment by nick-morhun** [comment]
Also setting overrideReferences to true in asmdef files should clean up generated C# projects

**Comment by acoppes** [comment]
thanks for adding the issue and sorry I didn't read it before, will consider what you suggested.
