### ISSUE TITLE
Neither Package Manager command works

### ISSUE THREAD

**Issue by OneManMonkeySquad** [acoppes/unity-history-window#28]
Neither
_https://github.com/acoppes/unity-history-window.git#1.0.6_
nor
_https://github.com/acoppes/unity-history-window.git#1.0.4_
works in 2021.1.7. Error:
_[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/acoppes/unity-history-window.git#1.0.6]:
  Could not clone [https://github.com/acoppes/unity-history-window.git]. Revision [1.0.6] could not be found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()_

Am I doing something wrong? Tried different ways, git and https syntax, no specific version. :(

**Comment by acoppes** [comment]
Just tested it using https://github.com/acoppes/unity-history-window.git#1.0.6 and Unity 2020.3.5f1, have to test it again in 2021, maybe something changed in specifying package dependencies with https or git url.

**Comment by acoppes** [comment]
It works with 2021.2.0a10 too, maybe you are doing something wrong?
