### ISSUE TITLE
Compiler warnings break builds in strict build pipelines

### ISSUE THREAD

**Issue by roger-o3h** [acoppes/unity-history-window#35]
Hiya! Thanks for your work on this plugin and generosity in sharing it!

In our automated build environment, we don't allow compiler warnings, by inserting `-warnaserror` into our `csc.rsp` file.

Unfortunately that means we can't take advantage of your lovely plugin via UPM, where of course the source is read-only.

Hopefully these are pretty easy to clear up, I'd love to share this with the team. Thank you!

```
24: [Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Gemserk.SelectionHistory.Editor.dll
25: [Unity] Library\PackageCache\com.gemserk.selectionhistory@1.1.6\Editor\SelectionHistoryWindow.cs(112,27): error CS0219: The variable 'lastObject' is assigned but its value is never used
26: [Unity] Library\PackageCache\com.gemserk.selectionhistory@1.1.6\Editor\SelectionHistoryWindow.cs(112,27): error CS0219: The variable 'lastObject' is assigned but its value is never used
```

**Comment by acoppes** [comment]
Hi, it is already fixed, will be there in version 1.1.7.

In the future, feel free to send my a pull request with a proper fix so I can just merge it and upload new version if you want, otherwise I could be a bit slow in fixing stuff.
