### ISSUE TITLE
Allow opening prefab from Favorites with double click

### ISSUE THREAD

**Issue by Hegemege** [acoppes/unity-history-window#44]
Optionally, allow changing the behaviour of what clicking items does in the Favorites window (select in Project / Open prefab, much like how this option is for the Unity Search (previously Quick Search) of Open asset vs Select asset).

I use the window to quickly navigate between different prefabs when I'm working on features. I've been using the Search popup and typing the name, but it's just way too slow when I want to instantly open a prefab to work on it from my favorites.

Current behaviour that selects the prefab from Project window allows me to at at least then move my mouse over to the Project window, and double click the highlighted prefab to open, but I feel like I want to do it directly from the Favorites window. I've docked the Favorites right next to Project, but I thought this would be useful.

**Comment by acoppes** [comment]
It sounds interesting, what do you think about an extra button to the side, next to the remove icon, to open a prefab in case it is a prefab.

![image](https://github.com/acoppes/unity-history-window/assets/591852/ca5452eb-4f58-400d-bddb-8cff5ba73373)

I could change the double click too (not sure how but it must be possible), but in this way it is clear that there is an open prefab option.

**Comment by acoppes** [comment]
I implemented both options, double click on prefab elements in history and favorites window and also added the eye button, it will be released in version 1.1.17.

**Comment by Hegemege** [comment]
Thanks, it works great! First open was indeed a bit glitchy but I opened it again, and restarted Unity and it's working flawlessly so far.
