### ISSUE TITLE
Selection delay in big scene

### ISSUE THREAD

**Issue by pkosyakov** [acoppes/unity-history-window#45]
I have scene with about 10 000 gameobjects. On each selection I get delay 2-4 seconds which frustrating. After closing Selection plugin window problem disappears.

**Comment by acoppes** [comment]
How big is the selection history?, can you try reducing it to see if it improves, I'm not sure but could be related with having to convert objects to global id, can you try (different test) turning off the hierarchy history?

**Comment by pkosyakov** [comment]
I have cleared the history and cannot reproduce the defect. I.e. it was not related to the number of objects in the scene. if it happens again, I will write

**Comment by acoppes** [comment]
I've improved window performance in latest version, hope this helps in reducing these delays, will close the issue for now but reopen it if you still see those delays.
