### ISSUE TITLE
Bad styling when using Light editor theme

### ISSUE THREAD

**Issue by Cardinal90** [acoppes/unity-history-window#54]
Unfortunately recent versions are unusable with Light theme. At least before you could see text well, if not icons. Here is a screenshot of how it looks in 1.5.5:

![7CxAL2o](https://github.com/user-attachments/assets/bc2768b5-8791-4c35-9b25-55153ea4dea3)

**Comment by acoppes** [comment]
Completely agree, unusable, sorry for that, will take a look at it in the next days.

**Comment by acoppes** [comment]
Just uploaded a new version that should fix the styling issues for light theme. Thanks for reporting it.
