### ISSUE TITLE
Add favorites section

### ISSUE THREAD

**Issue by rgarat** [acoppes/unity-history-window#9]
It would be interesting to be able to mark some items in the history as favorites, and have them stay always on top, and have reserved positions in the history, so they are never removed due to overflow.

Maybe even have them fixed and out of the scrollable area

**Comment by acoppes** [comment]
I like it, could be a section yeah or another window, have to give it a try to see what is best. Maybe the favorites section could accept drag & drop to it, to add new items.

**Comment by acoppes** [comment]
Added basic implementation for this feature, check it if you can and give me some feedback. Right now you can enable/disable it in Preferences (it is enabled by default), it allows you to pin/unpin objects from the history to the favorites (rendered together in the same window but favorites are always there).
